### ISSUE TITLE
Multiple instances OFF behavior

### ISSUE THREAD

**Issue by AtmanActive** [portapps/thunderbird-portable#12]
Hi @crazy-max,

First of all kudos and thank you for your wonderful work on portapps.io, it is greatly appreciated. I am using almost all of them.

Now, I noticed something different in behavior of the portable launcher of, for example, rambox-portable versus this one: when I have RamboxPortable running, and then I execute _rambox-portable.exe_ this is what happens: 

- if Rambox is the active window, nothing happens
- if Rambox is minimized, it just shows up in the foreground and takes over the focus

Perfect. That's exactly how I prefer it to be.

But, for _stormhen-portable.exe_ whether Thunderbird is active or not, I get an error window with a message: "Other instance detected. You have to enable multiple instances in your configuration if you want to launch another instance". Which is absolutely something I don't want.

Hence, my question: how do I make _stormhen-portable.exe_ behave exactly the same as _rambox-portable.exe_ described above?

Thanks.

**Comment by crazy-max** [comment]
Hi @AtmanActive,

> - if Rambox is the active window, nothing happens
> - if Rambox is minimized, it just shows up in the foreground and takes over the focus

That's a behavior linked to Rambox not the Portapps wrapper.

> But, for _stormhen-portable.exe_ whether Thunderbird is active or not, I get an error window with a message: "Other instance detected. You have to enable multiple instances in your configuration if you want to launch another instance". Which is absolutely something I don't want.

It's a behaviour of the Thunderbird that I have to manage and that's why you have this message to avoid launching another instance by mistake because Mozilla's products don't find an existing instance compared to Rambox (based on Electron).

>Hence, my question: how do I make _stormhen-portable.exe_ behave exactly the same as _rambox-portable.exe_ described above?

So there is no way today to have this behavior on Thunderbird unless Mozilla implements it on its side.

> First of all kudos and thank you for your wonderful work on portapps.io, it is greatly appreciated. I am using almost all of them.

Thanks! Glad you like it :)

**Comment by AtmanActive** [comment]
Is it not possible to manage something like that from the portable launcher?

**Comment by crazy-max** [comment]
@AtmanActive I don't want the wrapper to interact with the application, except for its initial execution.
