### ISSUE TITLE
Unable to open the summary file ....

### ISSUE THREAD

**Issue by yardstudio** [portapps/thunderbird-portable#22]
I have 5 IMAP accounts, 2 ExQuilla Office365 accounts. When TB starting often cause error "Unable to open the summary file ...." on different folders.

This happend not from start, but after using email client in production

Deleting *.msf files solving sometimes, but error caused again, in one other folder or subfolder. Most often is now error in inbox.

I was try disable all plugins, nothing helped

![2020-07-07_17-20-21](https://user-images.githubusercontent.com/25852179/86804838-92843300-c077-11ea-8e01-f11738ee786f.png)

**Comment by crazy-max** [comment]
Please create a proper [bug report](https://github.com/portapps/stormhen-portable/issues/new?template=bug_report.md).
