### ISSUE TITLE
Download going to 404

### ISSUE THREAD

**Issue by yardstudio** [portapps/thunderbird-portable#32]
https://portapps.io/download/stormhen-portable-win64-78.3.1-37-setup.exe
or direct dovnload from Git going to 404

![2020-11-04_16-45-22](https://user-images.githubusercontent.com/25852179/98134618-38796a00-1ebf-11eb-9b02-94763795340e.png)

**Comment by crazy-max** [comment]
@yardstudio Thanks the link is wrong. This should be fixed now.
