### ISSUE TITLE
Missing 2 Feature or I'm a noob

### ISSUE THREAD

**Issue by Himusaki** [portapps/thunderbird-portable#47]
I wanted to know where is the option to enable/disable Run this app on Startup?

How to trust this application build so that i can add personal emails too

Thanks for the hardwork

**Comment by crazy-max** [comment]
@Himusaki 

> I wanted to know where is the option to enable/disable Run this app on Startup?

Suggest to put a shortcut to `stormhen-portable.exe` in the startup folder on Windows.

> How to trust this application build so that i can add personal emails too

https://portapps.io/doc/faq/#how-to-trust-your-distributed-binaries
